name: Build

on: [push]

jobs:
  test:
    runs-on: macos-latest

    env: 
      SONA_USER: ${{ secrets.SONA_USER }}
      SONA_PASS: ${{ secrets.SONA_PASS }}

    strategy:
      fail-fast: false
      matrix:
        api-level:
          # Test against the API 17, as the API 16 raises an error:
          # `com.android.ddmlib.InstallException: Unknown failure: Error: Unknown option: -d`
          # `usage: pm list packages [-f] [-d] [-e] [-s] [-3] [-i] [-u] [FILTER]`
#          - 17 
#          - 24
          - 29

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Test upload
#        run: ./gradlew publish --no-parallel closeAndReleaseRepository
        run: ./gradlew uploadArchives
